# Site wide configuration

title: Isha
locale: en_US
description: Wherein I try to use words.
logo: site-logo.png
search: true
#url: http://isha.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Isha
  avatar: isha.jpg
  email: isha.kumaarr@gmail.com
  disqus-shortname:
  twitter: IshaKumaarr
  facebook: #username
  github: isha
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: ishakumaarr
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
